services:
  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    env_file: .env
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
      - ./db:/app/db
    restart: unless-stopped
