# Generated by Django 5.2.7 on 2025-10-19 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='signuprequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signuprequest',
            name='decision_note',
            field=models.TextField(blank=True, help_text='Nota del administrador sobre la decisión'),
        ),
    ]
