services:
  jitsi:
    image: jitsi/web:stable
    container_name: jitsi-meet
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - JITSI_DOMAIN=${JITSI_DOMAIN:-localhost}
      - PUBLIC_URL=${PUBLIC_URL:-http://localhost:8080}
      - ENABLE_AUTH=${ENABLE_AUTH:-false}
      - ENABLE_GUESTS=1
      - ENABLE_WELCOME_PAGE=1
    volumes:
      - ./logs:/var/log/jitsi
