version: '3'

# Volúmenes para persistencia de configuraciones
volumes:
  prosody-config:
  jicofo-config:
  jvb-config:

services:
  # Frontend
  web:
    image: jitsi/web:stable
    container_name: jitsi-web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./logs:/var/log/jitsi
    env_file:
      - .env
    environment:
      - ENABLE_AUTH=0
      - ENABLE_GUESTS=1
      - ENABLE_WELCOME_PAGE=1
    networks:
      - jitsi

  # XMPP server
  prosody:
    image: jitsi/prosody:stable
    container_name: jitsi-prosody
    restart: unless-stopped
    ports:
      - "5222:5222"
      - "5280:5280"
    volumes:
      - prosody-config:/config
      - ./logs:/var/log/jitsi
    env_file:
      - .env
    environment:
      - ENABLE_AUTH=0
    networks:
      - jitsi

  # Focus component
  jicofo:
    image: jitsi/jicofo:stable
    container_name: jitsi-jicofo
    restart: unless-stopped
    volumes:
      - jicofo-config:/config
      - ./logs:/var/log/jitsi
    env_file:
      - .env
    environment:
      - ENABLE_AUTH=0
    depends_on:
      - prosody
    networks:
      - jitsi

  # Video bridge
  jvb:
    image: jitsi/jvb:stable
    container_name: jitsi-jvb
    restart: unless-stopped
    ports:
      - "10000:10000/udp"
    volumes:
      - jvb-config:/config
      - ./logs:/var/log/jitsi
    env_file:
      - .env
    environment:
      - ENABLE_AUTH=0
    depends_on:
      - prosody
    networks:
      - jitsi

networks:
  jitsi:
