version: '3'

# Volúmenes para persistencia de configuraciones
volumes:
  prosody-config:
  jicofo-config:
  jvb-config:

services:
  # Frontend
  web:
    image: jitsi/web:stable
    container_name: jitsi-web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./logs:/var/log/jitsi
      - ./config/jitsi/meet-config.js:/usr/share/jitsi-meet/interface_config.js:ro
    env_file:
      - .env
    environment:
      - ENABLE_AUTH=0
      - ENABLE_GUESTS=1
      - ENABLE_WELCOME_PAGE=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - jitsi

  # XMPP server
  prosody:
    image: jitsi/prosody:stable
    container_name: jitsi-prosody
    restart: unless-stopped
    ports:
      - "5222:5222"
      - "5280:5280"
    volumes:
      - prosody-config:/config
      - ./logs:/var/log/jitsi
      - ./config/prosody/prosody-jitsi.cfg.lua:/etc/prosody/conf.d/jitsi-meet.cfg.lua:ro
    env_file:
      - .env
    environment:
      - ENABLE_AUTH=0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5280/http-bind/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - jitsi

  # Focus component
  jicofo:
    image: jitsi/jicofo:stable
    container_name: jitsi-jicofo
    restart: unless-stopped
    volumes:
      - jicofo-config:/config
      - ./logs:/var/log/jitsi
      - ./config/jicofo/jicofo.conf:/etc/jitsi/jicofo/jicofo.conf:ro
    env_file:
      - .env
    environment:
      - ENABLE_AUTH=0
    depends_on:
      - prosody
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/about/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - jitsi

  # Video bridge
  jvb:
    image: jitsi/jvb:stable
    container_name: jitsi-jvb
    restart: unless-stopped
    ports:
      - "10000:10000/udp"
    volumes:
      - jvb-config:/config
      - ./logs:/var/log/jitsi
      - ./config/jvb/jvb.conf:/etc/jitsi/videobridge/jvb.conf:ro
    env_file:
      - .env
    environment:
      - ENABLE_AUTH=0
    depends_on:
      - prosody
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/about/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - jitsi

networks:
  jitsi:
