services:
  jitsi:
    build: .
    container_name: jitsi-meet
    restart: unless-stopped
    ports:
      - "8080:80"
      - "10000:10000/udp"
    environment:
      - JITSI_DOMAIN=${JITSI_DOMAIN:-localhost}
      - PUBLIC_URL=${PUBLIC_URL:-http://localhost:8080}
      - ENABLE_AUTH=${ENABLE_AUTH:-true}
      - ENABLE_GUESTS=1
      - ENABLE_WELCOME_PAGE=1
    volumes:
      - ./logs:/var/log/jitsi
      - ../django/db/db.sqlite3:/config/sqlite/jitsi-django.sqlite3:ro
      - ./prosody-config:/prosody-plugins-custom
