version: '3.8'

services:
  # Prosody XMPP Server
  prosody:
    image: jitsi/prosody:stable-9254-1
    container_name: jitsi-prosody
    restart: unless-stopped
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
      - "5281:5281"
    volumes:
      - ./config/prosody:/config
      - ./logs/prosody:/var/log/prosody
    environment:
      - AUTH_TYPE=internal
      - ENABLE_AUTH=1
      - ENABLE_GUESTS=1
      - GLOBAL_MODULES=global_modules
      - GLOBAL_CONFIG=global_config
      - XMPP_DOMAIN=${JITSI_DOMAIN:-meet.jitsi}
      - XMPP_AUTH_DOMAIN=${JITSI_AUTH_DOMAIN:-auth.meet.jitsi}
      - XMPP_GUEST_DOMAIN=${JITSI_GUEST_DOMAIN:-guest.meet.jitsi}
      - XMPP_MUC_DOMAIN=${JITSI_MUC_DOMAIN:-muc.meet.jitsi}
      - XMPP_INTERNAL_MUC_DOMAIN=${JITSI_INTERNAL_MUC_DOMAIN:-internal-muc.meet.jitsi}
      - XMPP_RECORDER_DOMAIN=${JITSI_RECORDER_DOMAIN:-recorder.meet.jitsi}
      - JICOFO_COMPONENT_SECRET=${JICOFO_COMPONENT_SECRET:-JvbSecret}
      - JICOFO_AUTH_USER=${JICOFO_AUTH_USER:-focus}
      - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD:-JvbSecret}
      - JVB_AUTH_USER=${JVB_AUTH_USER:-jvb}
      - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD:-JvbSecret}
      - JIGASI_XMPP_USER=${JIGASI_XMPP_USER:-jigasi}
      - JIGASI_XMPP_PASSWORD=${JIGASI_XMPP_PASSWORD:-JvbSecret}
      - JIBRI_RECORDER_USER=${JIBRI_RECORDER_USER:-recorder}
      - JIBRI_RECORDER_PASSWORD=${JIBRI_RECORDER_PASSWORD:-JvbSecret}
      - JIBRI_XMPP_USER=${JIBRI_XMPP_USER:-jibri}
      - JIBRI_XMPP_PASSWORD=${JIBRI_XMPP_PASSWORD:-JvbSecret}
      - JWT_APP_ID=${JWT_APP_ID:-django-jitsi}
      - JWT_APP_SECRET=${JWT_APP_SECRET:-JvbSecret}
      - JWT_ACCEPTED_ISSUERS=${JWT_ACCEPTED_ISSUERS:-django-jitsi}
      - JWT_ACCEPTED_AUDIENCES=${JWT_ACCEPTED_AUDIENCES:-django-jitsi}
      - JWT_ASAP_KEYSERVER=https://prosody.${JITSI_DOMAIN:-meet.jitsi}/asap
      - JWT_ALLOW_EMPTY=0
      - JWT_AUTH_TYPE=token
      - JWT_TOKEN_AUTH_MODULE=token_verification
      - LOG_LEVEL=info
    networks:
      - jitsi

  # Jicofo - Focus component
  jicofo:
    image: jitsi/jicofo:stable-9254-1
    container_name: jitsi-jicofo
    restart: unless-stopped
    volumes:
      - ./config/jicofo:/config
    environment:
      - AUTH_TYPE=internal
      - ENABLE_AUTH=1
      - XMPP_DOMAIN=${JITSI_DOMAIN:-meet.jitsi}
      - XMPP_AUTH_DOMAIN=${JITSI_AUTH_DOMAIN:-auth.meet.jitsi}
      - XMPP_INTERNAL_MUC_DOMAIN=${JITSI_INTERNAL_MUC_DOMAIN:-internal-muc.meet.jitsi}
      - XMPP_SERVER=prosody
      - JICOFO_COMPONENT_SECRET=${JICOFO_COMPONENT_SECRET:-JvbSecret}
      - JICOFO_AUTH_USER=${JICOFO_AUTH_USER:-focus}
      - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD:-JvbSecret}
      - JICOFO_RESERVATION_REST_BASE_URL=
      - JVB_BREWERY_MUC=jvbbrewery
      - JIGASI_BREWERY_MUC=jigasibrewery
      - JIGASI_SIP_URI=
      - JIBRI_BREWERY_MUC=jibribrewery
      - JIBRI_PENDING_TIMEOUT=90
      - JVB_ENABLE_APIS=xmpp
      - TZ=UTC
    depends_on:
      - prosody
    networks:
      - jitsi

  # JVB - Jitsi Videobridge
  jvb:
    image: jitsi/jvb:stable-9254-1
    container_name: jitsi-jvb
    restart: unless-stopped
    ports:
      - "10000:10000/udp"
      - "4443:4443"
    volumes:
      - ./config/jvb:/config
    environment:
      - DOCKER_HOST_ADDRESS=${DOCKER_HOST_ADDRESS:-localhost}
      - XMPP_AUTH_DOMAIN=${JITSI_AUTH_DOMAIN:-auth.meet.jitsi}
      - XMPP_INTERNAL_MUC_DOMAIN=${JITSI_INTERNAL_MUC_DOMAIN:-internal-muc.meet.jitsi}
      - XMPP_SERVER=prosody
      - JVB_AUTH_USER=${JVB_AUTH_USER:-jvb}
      - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD:-JvbSecret}
      - JVB_BREWERY_MUC=jvbbrewery
      - JVB_PORT=10000
      - JVB_TCP_HARVESTER_DISABLED=true
      - JVB_TCP_PORT=4443
      - JVB_TCP_MAPPED_PORT=4443
      - JVB_OCTO_BIND_ADDRESS=${JVB_OCTO_BIND_ADDRESS:-0.0.0.0}
      - JVB_OCTO_PUBLIC_ADDRESS=${JVB_OCTO_PUBLIC_ADDRESS:-localhost}
      - JVB_STUN_SERVERS=${JVB_STUN_SERVERS:-stun.l.google.com:19302,stun1.l.google.com:19302}
      - JVB_ENABLE_APIS=xmpp
      - TZ=UTC
    depends_on:
      - prosody
    networks:
      - jitsi

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: jitsi-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - prosody
      - jicofo
      - jvb
    networks:
      - jitsi

networks:
  jitsi:
    driver: bridge